name: build diskimage - centos-bootc
run-name: building diskimage - centos-bootc
on:
  workflow_dispatch:

env:
    DISK_TYPE: qcow2
    ROOTFS: xfs
    ARCH: amd64
    BIB_IMAGE: quay.io/centos-bootc/bootc-image-builder:latest

jobs:
  build:
    name: build-diskimage-centos
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    steps:
    - name: Remove unwanted stuff
      uses: gbraad-actions/remove-unwanted@v1

    - uses: actions/checkout@v4

    - name: Workaround podman issues in GH actions
      run: |
        # see https://github.com/osbuild/bootc-image-builder/issues/446
        sudo rm -rf /var/lib/containers/storage
        sudo mkdir -p /etc/containers
        echo -e "[storage]\ndriver = \"overlay\"\nrunroot = \"/run/containers/storage\"\ngraphroot = \"/var/lib/containers/storage\"" | sudo tee /etc/containers/storage.conf

    - name: Workarounds for GH runner diskspace
      run: |
        sudo mkdir -p /mnt/var/lib/containers
        sudo mount -o bind /mnt/var/lib/containers /var/lib/containers
        sudo mkdir /var/lib/containers/storage

    - name: Create empty user configuration
      run: touch config.toml

    - name: Build image - centos
      id: build-image-dotfiles
      run: |
        mkdir -p ./output
        sudo podman pull ${{ env.IMAGE_NAME }}
        sudo podman run \
          --rm \
          -it \
          --privileged \
          --pull=newer \
          --security-opt label=type:unconfined_t \
          -v ./config.toml:/config.toml:ro \
          -v ./output:/output \
          -v /var/lib/containers/storage:/var/lib/containers/storage \
          ${{ env.BIB_IMAGE }} \
          --target-arch ${{ env.ARCH }} \
          --type ${{ env.DISK_TYPE }} \
          --rootfs ${{ env.ROOTFS }} \
          --local \
          ${{ env.IMAGE_NAME }}
      env:
        IMAGE_NAME: ghcr.io/gbraad-dotfiles/centos-bootc:latest

    - name: Rename output file - dotfiles
      run: sudo mv ./output/qcow2/disk.qcow2 ./output/qcow2/centos-disk.qcow2

#    - name: Upload Artifact - dotfiles
#      uses: actions/upload-artifact@v4
#      with:
#        name: dotfiles-disk
#        path: |
#          ./output/qcow2/centos-disk.qcow2
#        retention-days: 5

    - name: Set release tag
      id: get-tag
      run: |
        echo "TAG=$(date +'%y%m%d')" >> $GITHUB_OUTPUT

    - name: Wrap disk image in container
      run: |
        podman build -t ghcr.io/gbraad-dotfiles/centos-disk:latest \
          -f .devcontainer/centos/Containerfile-disk .

    - name: Tag image container
      run: |
        podman tag ghcr.io/gbraad-dotfiles/centos-disk:latest \
          ghcr.io/gbraad-dotfiles/centos-disk:stream9
        podman tag ghcr.io/gbraad-dotfiles/centos-disk:latest \
          ghcr.io/gbraad-dotfiles/centos-disk:${{steps.get-tag.outputs.TAG}}

    - name: Login to registry
      run: |
        podman login ghcr.io -u ${{ github.actor }} \
          -p ${{ secrets.GITHUB_TOKEN }}

    - name: Push image container to registry
      run: |
        podman push ghcr.io/gbraad-dotfiles/centos-disk:latest
        podman push ghcr.io/gbraad-dotfiles/centos-disk:stream9
        podman push ghcr.io/gbraad-dotfiles/centos-disk:${{steps.get-tag.outputs.TAG}}
