name: reusable-tailscale-ssh-machine

on:
  workflow_call:
    inputs:
      prefix_name:
        description: "Name of the container to run with machine (e.g., dotfedora, dotdebian)"
        required: true
        type: string
      runs-on:
        description: "Target runner"
        required: true
        type: string
        default: "ubuntu-latest"

jobs:
  dotfiles-test:
    runs-on: ${{ inputs.runs-on }}
    
    steps:

      - name: Enable linger and create user session (workaround)
        uses: gbraad-actions/blacksmith-user-session@main

      - name: Allow unprivileged userns (workaround)
        uses: gbraad-actions/warpbuild-unprivileged-userns@main

      - name: Get last 3 chars of hostname
        id: runner_id
        run: |
          echo "last3=${HOSTNAME: -3}" >> $GITHUB_OUTPUT

      #- name: Remove unwanted stuff
      #  uses: gbraad-devenv/remove-unwanted@v1

      - name: Tailscale setup (host)
        uses: gbraad-actions/tailscale-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          args: --ssh --accept-dns=false --operator=runner --advertise-exit-node
          hostname: "dotfiles-${{ steps.runner_id.outputs.last3 }}"

      - name: Dotfiles (install from action)
        uses: gbraad-dotfiles/install-action@main
        with:
          upstream: true

      - name: Write machinekey
        uses: gbraad-dotfiles/machinekey-action@main
        with:
          ssh_private_key: ${{ secrets.SSH_MACHINE_PRIVATE }}
          ssh_public_key: ${{ secrets.SSH_MACHINE_PUBLIC }}

      - name: Install required virtualization software
        continue-on-error: true
        uses: gbraad-actions/setup-virtualization@v2

      - name: Install containers tools (optional)
        continue-on-error: true
        uses: gbraad-actions/setup-container-tools@v1

      - name: Install macadam
        uses: gbraad-actions/zsh-action@main
        with:
          as_user: runner
          run: |
            apps macadam install

      - name: Run machine command - create machine
        uses: gbraad-dotfiles/machine-action@main
        with:
          prefix: ${{ inputs.prefix_name }}
          command: create

      #- name: Run machine command - start machine
      #  uses: gbraad-dotfiles/machine-action@main
      #  with:
      #    prefix: ${{ inputs.prefix_name }}
      #    command: start

      # unsure to run a new session; need to add `as_user` to the action itself?
      - name: Run machine command - start machine
        uses: gbraad-actions/zsh-action@main
        with:
          as_user: runner
          run: |
            machine ${{ inputs.prefix_name }} start

      # zsh-action because of the machine command
      - name: Tailscale setup (machine)
        id: tailscale-machine
        uses: gbraad-actions/zsh-action@main
        with:
          as_user: runner
          run: |
            sleep 1
            until machine ${{ inputs.prefix_name }} sudo tailscale up \
              --auth-key ${{ secrets.TAILSCALE_AUTHKEY_DEVENV }} \
              --hostname ${{ inputs.prefix_name }}-${{ steps.runner_id.outputs.last3 }} \
              --ssh --accept-dns=false \
              --operator=gbraad \
              --advertise-exit-node
            do
                sleep 0.1
            done

            IP=`machine ${{ inputs.prefix_name }} exec tailscale ip -4`
            echo "ip=${IP}" >> $GITHUB_OUTPUT


      # using run otherwise issues with backticks occur
      - name: Hang around
        run: |
          # get values from results file
          IP=`grep '^ip=' ${{ steps.tailscale-machine.outputs.results }} | cut -d= -f2`
          echo "Use the following command to connect \`tailscale ssh gbraad@${IP}\` or \`rshell gbraad@${IP}\`"

          IP=`tailscale ip -4`
          echo "Use the following command to debug from the host \`tailscale ssh runner@${IP}\` or \`rshell runner@${IP}\`"
          sleep 18000

      - name: Message user; 1 hour
        run: |
          sudo wall "about 1 hour remaining"
          sleep 1800

      - name: Message user; 20 minutes
        run: |
          sudo wall "20 minutes remaining"
          sleep 1200

      - name: Hang around
        run: |
          sleep infinity
